# Generated by Django 2.2.10 on 2021-04-11 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210411_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='survey_id',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='answerfield',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='surveyfield',
            old_name='survey_id',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='surveyfieldchoice',
            old_name='field_id',
            new_name='field',
        ),
        migrations.RemoveField(
            model_name='answertextfield',
            name='answer_field_id',
        ),
        migrations.AddField(
            model_name='answertextfield',
            name='answer_field',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='text_field', to='main.AnswerField'),
            preserve_default=False,
        ),
    ]
